
services:
  app:
    image: my_java17_app
    container_name: my_java_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    networks:
      - mynetwork
    depends_on:
      - dbmysql

  dbmysql:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: gte
      MYSQL_DATABASE: gpro
      MYSQL_PASSWORD: gte
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql_data:
  src:
  target:

networks:
  mynetwork:
    driver: bridge
