version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: my_java_app
    build:
      context: ./app
      dockerfile: Backend_Jenkins\Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - mynetwork
    depends_on:
      - dbmongo

  dbmongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:
  app:

networks:

  mynetwork:
    driver: bridge

