services:
  app:
    image: my_java17_app
    container_name: my_java_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    networks:
      - mynetwork
    depends_on:
      - dbmongo

  dbmongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mynetwork

volumes:
  mongo_data:
  src:
  target:
networks:

  mynetwork:
    driver: bridge

