pipeline {
    agent any
     tools {
            maven 'Maven'
        }
    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }
    triggers {
        pollSCM '*/1 * * * *'
    }
    stages {
        stage('Check Java Version') {
            steps {
                sh 'java -version'
                echo 'java version is checked'
            }
        }

        stage('Checkout') {
            steps {
                git credentialsId: '00445cc6-fdbd-4c9d-a46c-743ce3a67806', url: 'https://github.com/Arwa601/Backend_Jenkins', branch: 'main'
            }
        }

      stage('Build Docker Images') {
          steps {
              sh 'mvn clean package -DskipTests'
              sh 'docker compose build app dbmongo'


          }
      }

        stage('Run Services') {
            steps {
                script {

                    sh 'docker compose -f ${DOCKER_COMPOSE_FILE} up -d'
                }
            }
        }

        stage('Push to docker hub') {
            steps {
                 script {
                     withCredentials([string(credentialsId: 'dockerhub', variable: 'dockerhub')]) {

                      sh "echo $DOCKERHUB_TOKEN | docker login -u arwa409 --password-stdin"
                 }

                 sh 'docker push openjdk:17-jdk-slim'
                 sh 'docker push mongo:latest'
                 sh 'docker logout'
                }
            }
        }
    }

 }