pipeline {
    agent any
     tools {
            maven 'Maven'
        }
    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }
    triggers {
        pollSCM '*/1 * * * *'
    }
    stages {
        stage('Check Java Version') {
            steps {
                sh 'java -version'
                echo 'java version is checked'
            }
        }

        stage('Checkout') {
            steps {
                git credentialsId: '00445cc6-fdbd-4c9d-a46c-743ce3a67806', url: 'https://github.com/Arwa601/Backend_Jenkins', branch: 'main'
            }
        }
       stage ('Scan and Build Jar File')

                   steps{

                      withSonarQubeEnv(installationName: 'Production sonarQubeScanner', credentialsId: 'SonarQube_token')

                       sh 'mvn clean package sonar:sonar'

                       }
        }
      stage('Build Docker Images') {
          steps {
              sh 'mvn clean package -DskipTests'
              sh 'docker compose build app dbmongo'


          }
      }

        stage('Run Services') {
            steps {
                script {

                    sh 'docker compose -f ${DOCKER_COMPOSE_FILE} up -d'
                }
            }
        }

       stage('Push to Docker Hub') {
           steps {
               script {

                   withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                       sh "echo $DOCKER_PASSWORD | docker login -u arwa409 --password-stdin"
                   }

                   sh 'docker tag my_java17_app:latest arwa409/my_java17_app:latest'
                   sh 'docker tag mongo:latest arwa409/mongo:latest'

                   sh 'docker push arwa409/my_java17_app:latest'
                   sh 'docker push arwa409/mongo:latest'

                   sh 'docker logout'
               }
           }
       }
    }

 } }