pipeline {
    agent any
     tools {
            maven 'Maven'
        }
    environment {
        DOCKER_COMPOSE_FILE = 'docker-compose.yml'
    }
    triggers {
        pollSCM '*/1 * * * *'
    }
    stages {
        stage('Check Java Version') {
            steps {
                sh 'java -version'
                echo 'java version is checked'
            }
        }

        stage('Checkout') {
            steps {
                git credentialsId: '00445cc6-fdbd-4c9d-a46c-743ce3a67806', url: 'https://github.com/Arwa601/Backend_Jenkins', branch: 'main'
            }
        }

      stage('Build Docker Images') {
          steps {
              sh 'mvn clean package -DskipTests'
              sh 'docker compose build app dbmongo'


          }
      }

        stage('Run Services') {
            steps {
                script {

                    sh 'docker compose -f ${DOCKER_COMPOSE_FILE} up -d'
                }
            }
        }

        stage('Push to docker hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                    }
                    sh 'docker tag my_java17_app $DOCKER_USERNAME/my_java17_app'
                    sh 'docker tag mongo:latest $DOCKER_USERNAME/mongo:latest'
                    sh 'docker push $DOCKER_USERNAME/my_java17_app'
                    sh 'docker push $DOCKER_USERNAME/mongo:latest'
                    sh 'docker logout'
                }
            }
        }

    }

 }